version: '3'
services:
  backend:
    container_name: nestjs
    build: 
      context: ./ 
      dockerfile: Dockerfile
    image: nestjs
    ports:
     - "3000:9999"
    volumes:
     - ./usr/src/app

