version: '3'
services:
  backend:
    container_name: nestjs
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: nestjs/nestjs
    ports:
     - "3000:3000"
    volumes:
     - ./backend:/usr/src/app

